language: python
python:
  - "2.7"
# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
# Install packages
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
script: nosetests
