language: python
python:
  - "2.7"
before_install:
  - sudo rm -f /etc/boto.cfg
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "pip install -r requirements_test.txt"
script: nosetests
